# Task 1:

# 1.

# Write a function to compute 5/0 and use try/except to catch the exceptions.

In [2]:
def exception():
    try:
        a = int(input("Enter number:"))
        b = 5/a
        print("The code is working and answer is %0.2f"%b)
    except Exception as e:
        print(e)
        
exception()

Enter number: 0


division by zero


# 2.

# Implement a Python program to generate all sentences where 
# subject is in ["Americans","Indians"] and 
# verb is in ["Play", "watch"] and 
# the object is in ["Baseball","cricket"].
# Hint: Subject,Verb and Object should be declared in the program as shown below.
 subjects = ["Americans ","Indians"]\
 verbs = ["play","watch"]\
 objects = ["Baseball","Cricket"]

# Output should come as below:
 Americans play Baseball.\
 Americans play Cricket.\
 Americans watch Baseball.\
 Americans watch Cricket.\
 Indians play Baseball.\
 Indians play Cricket.\
 Indians watch Baseball.\
 Indians watch Cricket.

In [5]:
subjects = ["Americans","Indians"]
verbs = ["play","watch"]
objects = ["Baseball","Cricket"]
for i in range(len(subjects)):
    for j in range(len(verbs)):
        for k in range(len(objects)):
            print("%s %s %s." %(subjects[i],verbs[j],objects[k]))

Americans play Baseball.
Americans play Cricket.
Americans watch Baseball.
Americans watch Cricket.
Indians play Baseball.
Indians play Cricket.
Indians watch Baseball.
Indians watch Cricket.


# Task 2:

# 1.

# Write a function so that the columns of the output matrix are powers of the input vector.
# The order of the powers is determined by the increasing boolean argument. Specifically, when
# increasing is False, the i-th output column is the input vector raised element-wise to the power
# of N - i - 1.

# HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
# Theophile Vandermonde.

In [2]:
import numpy as n
s = int(input("Enter the size of values:"))
l = []
for i in range(s):
    v = int(input("Enter the value"))
    l.append(v)
a = n.array(l) 
m = n.column_stack([a**(s-i-1) for i in range(s)]) 
print(m)

Enter the size of values:5
Enter the value1
Enter the value2
Enter the value3
Enter the value4
Enter the value5
[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]
